import type { ParamDef } from '../core/params/params';
import type { SpectacleDef, SpectacleSection } from '../render/spectacle-contract';

/** Pure part of the Spectacle section: which numbers of a pack's spectacle get a slider. */
export interface SpectacleSlider {
  section: SpectacleSection;
  /** Path to the object that holds the number, inside the section ('' = the section itself). */
  path: string;
  key: string;
  label: string;
  def: Omit<ParamDef, 'default'>;
}

const slider = (
  section: SpectacleSection,
  path: string,
  key: string,
  label: string,
  min: number,
  max: number,
  unit: string,
  note: string,
  step?: number,
): SpectacleSlider => ({
  section,
  path,
  key,
  label,
  def: { min, max, unit, note, ...(step !== undefined ? { step } : {}) },
});

export const SPECTACLE_SLIDERS: readonly SpectacleSlider[] = [
  slider(
    'post',
    'bloom',
    'strength',
    'Bloom',
    0,
    3,
    '',
    'Glow around bright things (engines, shots, blasts). 0 = off.',
    0.05,
  ),
  slider(
    'post',
    'bloom',
    'radius',
    'Bloom spread',
    0,
    1,
    '',
    'How far the glow spreads. Higher = a softer, wider haze.',
    0.05,
  ),
  slider(
    'post',
    'bloom',
    'threshold',
    'Bloom threshold',
    0,
    1.5,
    '',
    'How bright something must be to glow. Lower = more things glow (white ships too); higher = only the lights.',
    0.02,
  ),
  slider(
    'post',
    'chromatic',
    'base',
    'Colour fringe',
    0,
    1,
    '',
    'Red and blue separate towards the screen edge, like a worn lens. 0 = none.',
    0.02,
  ),
  slider(
    'post',
    'chromatic',
    'hit',
    'Fringe on hit',
    0,
    1,
    '',
    'Extra fringe pulse when you are hit and on big kills.',
    0.05,
  ),
  slider('post', '', 'vignette', 'Vignette', 0, 1, '', 'Dark corners. 0 = none.', 0.02),
  slider('post', '', 'grain', 'Film grain', 0, 1, '', 'Animated film grain. 0 = none.', 0.02),
  slider(
    'post',
    '',
    'scanlines',
    'Scanlines',
    0,
    1,
    '',
    'Fine horizontal lines like a laser-disc master. 0 = none.',
    0.02,
  ),
  slider(
    'post',
    '',
    'punch',
    'Zoom punch',
    0,
    1,
    '',
    'How hard the picture pushes in on big kills (the camera is not touched). 0 = off.',
    0.05,
  ),
  slider(
    'backdrop',
    'nebula',
    'strength',
    'Gas clouds',
    0,
    1,
    '',
    'Opacity of the gas-cloud layers. 0 = clear sky.',
    0.02,
  ),
  slider(
    'backdrop',
    'nebula',
    'scale',
    'Cloud size',
    300,
    6000,
    'u',
    'Size of the cloud features in world units. Higher = bigger, calmer clouds.',
    50,
  ),
  slider(
    'backdrop',
    'nebula',
    'drift',
    'Cloud drift',
    0,
    200,
    'u/s',
    'How fast the gas drifts. 0 = still.',
    1,
  ),
  slider(
    'backdrop',
    'stars',
    'twinkle',
    'Star twinkle',
    0,
    1,
    '',
    'How much the extra star layers twinkle.',
    0.05,
  ),
  slider(
    'backdrop',
    'debris',
    'count',
    'Drifting rocks',
    0,
    64,
    'rocks',
    'How many rocks and wrecks drift in the mid-distance (the quality level caps it).',
    1,
  ),
  slider(
    'backdrop',
    'flashes',
    'rate',
    'Distant flashes',
    0,
    8,
    '/s',
    'Battle flashes per second far away (more when the fight is busy).',
    0.1,
  ),
  slider(
    'ships',
    'plume',
    'length',
    'Plume length',
    0,
    3,
    'radii',
    'Length of the engine flame at full throttle, in ship radii. 0 = no plume.',
    0.05,
  ),
  slider(
    'ships',
    'plume',
    'width',
    'Plume width',
    0,
    1,
    'radii',
    'Width of the flame at the nozzle, in ship radii.',
    0.02,
  ),
  slider(
    'ships',
    'plume',
    'idle',
    'Plume at idle',
    0,
    1,
    '',
    'Share of the plume that stays at idle throttle.',
    0.05,
  ),
  slider(
    'ships',
    'plume',
    'flicker',
    'Plume flicker',
    0,
    1,
    '',
    'How much the flame flickers.',
    0.05,
  ),
  slider(
    'ships',
    'plume',
    'shimmer',
    'Heat halo',
    0,
    1,
    '',
    'A pulsing glow at the nozzle (heat shimmer). 0 = none.',
    0.05,
  ),
  slider(
    'ships',
    'navLights',
    'size',
    'Nav lights',
    0,
    12,
    'u',
    'Size of the wingtip lights. 0 = off.',
    0.5,
  ),
  slider(
    'ships',
    'navLights',
    'blinkHz',
    'Strobe rate',
    0,
    4,
    'Hz',
    'Blinks per second of the white tail strobe. 0 = off.',
    0.1,
  ),
  slider(
    'ships',
    'trails',
    'width',
    'Trail width',
    0,
    30,
    'u',
    'Width of the wingtip trails. 0 = off.',
    0.5,
  ),
  slider('ships', 'trails', 'alpha', 'Trail opacity', 0, 1, '', 'Opacity of the trails.', 0.05),
  slider(
    'ships',
    'trails',
    'from',
    'Trails from speed',
    0,
    1,
    '',
    'Share of top speed from which the trails show.',
    0.02,
  ),
  slider(
    'ships',
    'rollStreak',
    'length',
    'Roll streak',
    0,
    400,
    'u',
    'Length of the helix streak behind a rolling ship. 0 = off.',
    5,
  ),
  slider(
    'ships',
    'missiles',
    'spirals',
    'Missile spirals',
    0,
    3,
    'strands',
    'Smoke strands twisting round each missile. 0 = plain trail.',
    1,
  ),
  slider(
    'ships',
    'missiles',
    'amplitude',
    'Spiral swing',
    0,
    40,
    'u',
    'How wide the spirals swing.',
    1,
  ),
  slider(
    'ships',
    'missiles',
    'smokeLife',
    'Smoke life',
    0.2,
    4,
    's',
    'How long missile smoke lingers.',
    0.1,
  ),
  slider(
    'ships',
    'missiles',
    'flash',
    'Launch flash',
    0,
    120,
    'u',
    'Size of the flash when a missile leaves. 0 = none.',
    1,
  ),
  slider(
    'ships',
    'brackets',
    'size',
    'Lock brackets',
    0,
    4,
    'x',
    'Size of the corner brackets that snap onto locked targets, as a multiple of their radius. 0 = off.',
    0.1,
  ),
  slider(
    'combat',
    'tracers',
    'glow',
    'Tracer glow',
    0.5,
    4,
    'x',
    'Brightness of bullet tracers and enemy orbs (above 1 they bloom).',
    0.1,
  ),
  slider(
    'combat',
    'tracers',
    'length',
    'Tracer length',
    4,
    200,
    'u',
    'Length of the glowing bullet streak.',
    1,
  ),
  slider(
    'combat',
    'tracers',
    'orb',
    'Enemy orb size',
    0,
    30,
    'u',
    'Radius of enemy plasma orbs. 0 = plain shots.',
    0.5,
  ),
];

/** The object a slider edits inside a spectacle, or null when the pack lacks that section. */
export function sliderTarget(
  spec: SpectacleDef,
  s: SpectacleSlider,
): Record<string, unknown> | null {
  const root = spec[s.section] as unknown as Record<string, unknown> | undefined;
  if (!root) return null;
  let at: unknown = root;
  for (const part of s.path ? s.path.split('.') : []) {
    at = (at as Record<string, unknown>)[part];
    if (typeof at !== 'object' || at === null) return null;
  }
  return typeof (at as Record<string, unknown>)[s.key] === 'number'
    ? (at as Record<string, unknown>)
    : null;
}
